apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm.fullname" . }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "vllm.selectorLabels" . | nindent 4 }}
{{- if .Values.externalService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm.fullname" . }}-external
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
  {{- with .Values.externalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
    - name: http
      port: {{ .Values.externalService.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "vllm.selectorLabels" . | nindent 4 }}
{{- end }}
